### ISSUE TITLE
Fix path

### ISSUE THREAD

**Issue by TiagoBehenck** [lucasmontano/rinha-de-compiler#2]
Hey, I think u forgot "." in this line.

`COPY ./var/rinha/source.rinha.json ./var/rinha/source.rinha.json `

https://github.com/lucasmontano/rinha-de-compiler/blob/3d526b8a392f859b3159a2840d56261adf2f03f4/Dockerfile#L14

**Comment by lucasmontano** [comment]
valeu @TiagoBehenck !
